# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class DeploymentLocation(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type: str=None, properties: object=None):
        """
        DeploymentLocation - a model defined in Swagger

        :param type: The type of this DeploymentLocation.
        :type type: str
        :param properties: The properties of this DeploymentLocation.
        :type properties: object
        """
        self.swagger_types = {
            'type': str,
            'properties': object
        }

        self.attribute_map = {
            'type': 'type',
            'properties': 'properties'
        }

        self._type = type
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt) -> 'DeploymentLocation':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The deploymentLocation of this DeploymentLocation.
        :rtype: DeploymentLocation
        """
        return deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """
        Gets the type of this DeploymentLocation.

        :return: The type of this DeploymentLocation.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """
        Sets the type of this DeploymentLocation.

        :param type: The type of this DeploymentLocation.
        :type type: str
        """

        self._type = type

    @property
    def properties(self) -> object:
        """
        Gets the properties of this DeploymentLocation.

        :return: The properties of this DeploymentLocation.
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties: object):
        """
        Sets the properties of this DeploymentLocation.

        :param properties: The properties of this DeploymentLocation.
        :type properties: object
        """

        self._properties = properties

