# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse2011Context(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, asynchronous_transition_response: bool=None):
        """
        InlineResponse2011Context - a model defined in Swagger

        :param asynchronous_transition_response: The asynchronous_transition_response of this InlineResponse2011Context.
        :type asynchronous_transition_response: bool
        """
        self.swagger_types = {
            'asynchronous_transition_response': bool
        }

        self.attribute_map = {
            'asynchronous_transition_response': 'AsynchronousTransitionResponse'
        }

        self._asynchronous_transition_response = asynchronous_transition_response

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2011Context':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_1_context of this InlineResponse2011Context.
        :rtype: InlineResponse2011Context
        """
        return deserialize_model(dikt, cls)

    @property
    def asynchronous_transition_response(self) -> bool:
        """
        Gets the asynchronous_transition_response of this InlineResponse2011Context.

        :return: The asynchronous_transition_response of this InlineResponse2011Context.
        :rtype: bool
        """
        return self._asynchronous_transition_response

    @asynchronous_transition_response.setter
    def asynchronous_transition_response(self, asynchronous_transition_response: bool):
        """
        Sets the asynchronous_transition_response of this InlineResponse2011Context.

        :param asynchronous_transition_response: The asynchronous_transition_response of this InlineResponse2011Context.
        :type asynchronous_transition_response: bool
        """

        self._asynchronous_transition_response = asynchronous_transition_response

