# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse200Properties(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, response_kafka_connection_url: str=None, response_kafka_topic_name: str=None):
        """
        InlineResponse200Properties - a model defined in Swagger

        :param response_kafka_connection_url: The response_kafka_connection_url of this InlineResponse200Properties.
        :type response_kafka_connection_url: str
        :param response_kafka_topic_name: The response_kafka_topic_name of this InlineResponse200Properties.
        :type response_kafka_topic_name: str
        """
        self.swagger_types = {
            'response_kafka_connection_url': str,
            'response_kafka_topic_name': str
        }

        self.attribute_map = {
            'response_kafka_connection_url': 'responseKafkaConnectionUrl',
            'response_kafka_topic_name': 'responseKafkaTopicName'
        }

        self._response_kafka_connection_url = response_kafka_connection_url
        self._response_kafka_topic_name = response_kafka_topic_name

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200Properties':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_properties of this InlineResponse200Properties.
        :rtype: InlineResponse200Properties
        """
        return deserialize_model(dikt, cls)

    @property
    def response_kafka_connection_url(self) -> str:
        """
        Gets the response_kafka_connection_url of this InlineResponse200Properties.

        :return: The response_kafka_connection_url of this InlineResponse200Properties.
        :rtype: str
        """
        return self._response_kafka_connection_url

    @response_kafka_connection_url.setter
    def response_kafka_connection_url(self, response_kafka_connection_url: str):
        """
        Sets the response_kafka_connection_url of this InlineResponse200Properties.

        :param response_kafka_connection_url: The response_kafka_connection_url of this InlineResponse200Properties.
        :type response_kafka_connection_url: str
        """

        self._response_kafka_connection_url = response_kafka_connection_url

    @property
    def response_kafka_topic_name(self) -> str:
        """
        Gets the response_kafka_topic_name of this InlineResponse200Properties.

        :return: The response_kafka_topic_name of this InlineResponse200Properties.
        :rtype: str
        """
        return self._response_kafka_topic_name

    @response_kafka_topic_name.setter
    def response_kafka_topic_name(self, response_kafka_topic_name: str):
        """
        Sets the response_kafka_topic_name of this InlineResponse200Properties.

        :param response_kafka_topic_name: The response_kafka_topic_name of this InlineResponse200Properties.
        :type response_kafka_topic_name: str
        """

        self._response_kafka_topic_name = response_kafka_topic_name

