# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.topologydeploymentlocationsnameinstances_properties import TopologydeploymentlocationsnameinstancesProperties
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse2004(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, resource_id: str=None, resource_name: str=None, resource_type: str=None, resource_manager_id: str=None, deployment_location: str=None, properties: TopologydeploymentlocationsnameinstancesProperties=None, created_at: date=None, last_modified_at: date=None):
        """
        InlineResponse2004 - a model defined in Swagger

        :param resource_id: The resource_id of this InlineResponse2004.
        :type resource_id: str
        :param resource_name: The resource_name of this InlineResponse2004.
        :type resource_name: str
        :param resource_type: The resource_type of this InlineResponse2004.
        :type resource_type: str
        :param resource_manager_id: The resource_manager_id of this InlineResponse2004.
        :type resource_manager_id: str
        :param deployment_location: The deployment_location of this InlineResponse2004.
        :type deployment_location: str
        :param properties: The properties of this InlineResponse2004.
        :type properties: TopologydeploymentlocationsnameinstancesProperties
        :param created_at: The created_at of this InlineResponse2004.
        :type created_at: date
        :param last_modified_at: The last_modified_at of this InlineResponse2004.
        :type last_modified_at: date
        """
        self.swagger_types = {
            'resource_id': str,
            'resource_name': str,
            'resource_type': str,
            'resource_manager_id': str,
            'deployment_location': str,
            'properties': TopologydeploymentlocationsnameinstancesProperties,
            'created_at': date,
            'last_modified_at': date
        }

        self.attribute_map = {
            'resource_id': 'resourceId',
            'resource_name': 'resourceName',
            'resource_type': 'resourceType',
            'resource_manager_id': 'resourceManagerId',
            'deployment_location': 'deploymentLocation',
            'properties': 'properties',
            'created_at': 'createdAt',
            'last_modified_at': 'lastModifiedAt'
        }

        self._resource_id = resource_id
        self._resource_name = resource_name
        self._resource_type = resource_type
        self._resource_manager_id = resource_manager_id
        self._deployment_location = deployment_location
        self._properties = properties
        self._created_at = created_at
        self._last_modified_at = last_modified_at

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.
        :rtype: InlineResponse2004
        """
        return deserialize_model(dikt, cls)

    @property
    def resource_id(self) -> str:
        """
        Gets the resource_id of this InlineResponse2004.

        :return: The resource_id of this InlineResponse2004.
        :rtype: str
        """
        return self._resource_id

    @resource_id.setter
    def resource_id(self, resource_id: str):
        """
        Sets the resource_id of this InlineResponse2004.

        :param resource_id: The resource_id of this InlineResponse2004.
        :type resource_id: str
        """

        self._resource_id = resource_id

    @property
    def resource_name(self) -> str:
        """
        Gets the resource_name of this InlineResponse2004.

        :return: The resource_name of this InlineResponse2004.
        :rtype: str
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name: str):
        """
        Sets the resource_name of this InlineResponse2004.

        :param resource_name: The resource_name of this InlineResponse2004.
        :type resource_name: str
        """

        self._resource_name = resource_name

    @property
    def resource_type(self) -> str:
        """
        Gets the resource_type of this InlineResponse2004.

        :return: The resource_type of this InlineResponse2004.
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type: str):
        """
        Sets the resource_type of this InlineResponse2004.

        :param resource_type: The resource_type of this InlineResponse2004.
        :type resource_type: str
        """

        self._resource_type = resource_type

    @property
    def resource_manager_id(self) -> str:
        """
        Gets the resource_manager_id of this InlineResponse2004.

        :return: The resource_manager_id of this InlineResponse2004.
        :rtype: str
        """
        return self._resource_manager_id

    @resource_manager_id.setter
    def resource_manager_id(self, resource_manager_id: str):
        """
        Sets the resource_manager_id of this InlineResponse2004.

        :param resource_manager_id: The resource_manager_id of this InlineResponse2004.
        :type resource_manager_id: str
        """

        self._resource_manager_id = resource_manager_id

    @property
    def deployment_location(self) -> str:
        """
        Gets the deployment_location of this InlineResponse2004.

        :return: The deployment_location of this InlineResponse2004.
        :rtype: str
        """
        return self._deployment_location

    @deployment_location.setter
    def deployment_location(self, deployment_location: str):
        """
        Sets the deployment_location of this InlineResponse2004.

        :param deployment_location: The deployment_location of this InlineResponse2004.
        :type deployment_location: str
        """

        self._deployment_location = deployment_location

    @property
    def properties(self) -> TopologydeploymentlocationsnameinstancesProperties:
        """
        Gets the properties of this InlineResponse2004.

        :return: The properties of this InlineResponse2004.
        :rtype: TopologydeploymentlocationsnameinstancesProperties
        """
        return self._properties

    @properties.setter
    def properties(self, properties: TopologydeploymentlocationsnameinstancesProperties):
        """
        Sets the properties of this InlineResponse2004.

        :param properties: The properties of this InlineResponse2004.
        :type properties: TopologydeploymentlocationsnameinstancesProperties
        """

        self._properties = properties

    @property
    def created_at(self) -> date:
        """
        Gets the created_at of this InlineResponse2004.

        :return: The created_at of this InlineResponse2004.
        :rtype: date
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: date):
        """
        Sets the created_at of this InlineResponse2004.

        :param created_at: The created_at of this InlineResponse2004.
        :type created_at: date
        """

        self._created_at = created_at

    @property
    def last_modified_at(self) -> date:
        """
        Gets the last_modified_at of this InlineResponse2004.

        :return: The last_modified_at of this InlineResponse2004.
        :rtype: date
        """
        return self._last_modified_at

    @last_modified_at.setter
    def last_modified_at(self, last_modified_at: date):
        """
        Sets the last_modified_at of this InlineResponse2004.

        :param last_modified_at: The last_modified_at of this InlineResponse2004.
        :type last_modified_at: date
        """

        self._last_modified_at = last_modified_at

