# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.inline_response200_properties import InlineResponse200Properties
from swagger_server.models.inline_response200_supported_features import InlineResponse200SupportedFeatures
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse200(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, version: str=None, supported_api_versions: List[str]=None, supported_features: InlineResponse200SupportedFeatures=None, properties: InlineResponse200Properties=None):
        """
        InlineResponse200 - a model defined in Swagger

        :param name: The name of this InlineResponse200.
        :type name: str
        :param version: The version of this InlineResponse200.
        :type version: str
        :param supported_api_versions: The supported_api_versions of this InlineResponse200.
        :type supported_api_versions: List[str]
        :param supported_features: The supported_features of this InlineResponse200.
        :type supported_features: InlineResponse200SupportedFeatures
        :param properties: The properties of this InlineResponse200.
        :type properties: InlineResponse200Properties
        """
        self.swagger_types = {
            'name': str,
            'version': str,
            'supported_api_versions': List[str],
            'supported_features': InlineResponse200SupportedFeatures,
            'properties': InlineResponse200Properties
        }

        self.attribute_map = {
            'name': 'name',
            'version': 'version',
            'supported_api_versions': 'supportedApiVersions',
            'supported_features': 'supportedFeatures',
            'properties': 'properties'
        }

        self._name = name
        self._version = version
        self._supported_api_versions = supported_api_versions
        self._supported_features = supported_features
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.
        :rtype: InlineResponse200
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this InlineResponse200.

        :return: The name of this InlineResponse200.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this InlineResponse200.

        :param name: The name of this InlineResponse200.
        :type name: str
        """

        self._name = name

    @property
    def version(self) -> str:
        """
        Gets the version of this InlineResponse200.

        :return: The version of this InlineResponse200.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """
        Sets the version of this InlineResponse200.

        :param version: The version of this InlineResponse200.
        :type version: str
        """

        self._version = version

    @property
    def supported_api_versions(self) -> List[str]:
        """
        Gets the supported_api_versions of this InlineResponse200.

        :return: The supported_api_versions of this InlineResponse200.
        :rtype: List[str]
        """
        return self._supported_api_versions

    @supported_api_versions.setter
    def supported_api_versions(self, supported_api_versions: List[str]):
        """
        Sets the supported_api_versions of this InlineResponse200.

        :param supported_api_versions: The supported_api_versions of this InlineResponse200.
        :type supported_api_versions: List[str]
        """

        self._supported_api_versions = supported_api_versions

    @property
    def supported_features(self) -> InlineResponse200SupportedFeatures:
        """
        Gets the supported_features of this InlineResponse200.

        :return: The supported_features of this InlineResponse200.
        :rtype: InlineResponse200SupportedFeatures
        """
        return self._supported_features

    @supported_features.setter
    def supported_features(self, supported_features: InlineResponse200SupportedFeatures):
        """
        Sets the supported_features of this InlineResponse200.

        :param supported_features: The supported_features of this InlineResponse200.
        :type supported_features: InlineResponse200SupportedFeatures
        """

        self._supported_features = supported_features

    @property
    def properties(self) -> InlineResponse200Properties:
        """
        Gets the properties of this InlineResponse200.

        :return: The properties of this InlineResponse200.
        :rtype: InlineResponse200Properties
        """
        return self._properties

    @properties.setter
    def properties(self, properties: InlineResponse200Properties):
        """
        Sets the properties of this InlineResponse200.

        :param properties: The properties of this InlineResponse200.
        :type properties: InlineResponse200Properties
        """

        self._properties = properties

