# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response202_context import InlineResponse202Context  # noqa: F401,E501
from swagger_server import util


class InlineResponse202(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, request_id: str=None, request_state: str=None, request_state_reason: str=None, request_failure_code: str=None, context: InlineResponse202Context=None):  # noqa: E501
        """InlineResponse202 - a model defined in Swagger

        :param request_id: The request_id of this InlineResponse202.  # noqa: E501
        :type request_id: str
        :param request_state: The request_state of this InlineResponse202.  # noqa: E501
        :type request_state: str
        :param request_state_reason: The request_state_reason of this InlineResponse202.  # noqa: E501
        :type request_state_reason: str
        :param request_failure_code: The request_failure_code of this InlineResponse202.  # noqa: E501
        :type request_failure_code: str
        :param context: The context of this InlineResponse202.  # noqa: E501
        :type context: InlineResponse202Context
        """
        self.swagger_types = {
            'request_id': str,
            'request_state': str,
            'request_state_reason': str,
            'request_failure_code': str,
            'context': InlineResponse202Context
        }

        self.attribute_map = {
            'request_id': 'requestId',
            'request_state': 'requestState',
            'request_state_reason': 'requestStateReason',
            'request_failure_code': 'requestFailureCode',
            'context': 'context'
        }

        self._request_id = request_id
        self._request_state = request_state
        self._request_state_reason = request_state_reason
        self._request_failure_code = request_failure_code
        self._context = context

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse202':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_202 of this InlineResponse202.  # noqa: E501
        :rtype: InlineResponse202
        """
        return util.deserialize_model(dikt, cls)

    @property
    def request_id(self) -> str:
        """Gets the request_id of this InlineResponse202.


        :return: The request_id of this InlineResponse202.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this InlineResponse202.


        :param request_id: The request_id of this InlineResponse202.
        :type request_id: str
        """

        self._request_id = request_id

    @property
    def request_state(self) -> str:
        """Gets the request_state of this InlineResponse202.


        :return: The request_state of this InlineResponse202.
        :rtype: str
        """
        return self._request_state

    @request_state.setter
    def request_state(self, request_state: str):
        """Sets the request_state of this InlineResponse202.


        :param request_state: The request_state of this InlineResponse202.
        :type request_state: str
        """
        allowed_values = ["PENDING", "IN_PROGRESS", "COMPLETED", "CANCELLED", "FAILED"]  # noqa: E501
        if request_state not in allowed_values:
            raise ValueError(
                "Invalid value for `request_state` ({0}), must be one of {1}"
                .format(request_state, allowed_values)
            )

        self._request_state = request_state

    @property
    def request_state_reason(self) -> str:
        """Gets the request_state_reason of this InlineResponse202.


        :return: The request_state_reason of this InlineResponse202.
        :rtype: str
        """
        return self._request_state_reason

    @request_state_reason.setter
    def request_state_reason(self, request_state_reason: str):
        """Sets the request_state_reason of this InlineResponse202.


        :param request_state_reason: The request_state_reason of this InlineResponse202.
        :type request_state_reason: str
        """

        self._request_state_reason = request_state_reason

    @property
    def request_failure_code(self) -> str:
        """Gets the request_failure_code of this InlineResponse202.


        :return: The request_failure_code of this InlineResponse202.
        :rtype: str
        """
        return self._request_failure_code

    @request_failure_code.setter
    def request_failure_code(self, request_failure_code: str):
        """Sets the request_failure_code of this InlineResponse202.


        :param request_failure_code: The request_failure_code of this InlineResponse202.
        :type request_failure_code: str
        """

        self._request_failure_code = request_failure_code

    @property
    def context(self) -> InlineResponse202Context:
        """Gets the context of this InlineResponse202.


        :return: The context of this InlineResponse202.
        :rtype: InlineResponse202Context
        """
        return self._context

    @context.setter
    def context(self, context: InlineResponse202Context):
        """Sets the context of this InlineResponse202.


        :param context: The context of this InlineResponse202.
        :type context: InlineResponse202Context
        """

        self._context = context
