# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse201(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, type: str=None, properties: object=None):
        """
        InlineResponse201 - a model defined in Swagger

        :param name: The name of this InlineResponse201.
        :type name: str
        :param type: The type of this InlineResponse201.
        :type type: str
        :param properties: The properties of this InlineResponse201.
        :type properties: object
        """
        self.swagger_types = {
            'name': str,
            'type': str,
            'properties': object
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type',
            'properties': 'properties'
        }

        self._name = name
        self._type = type
        self._properties = properties

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.
        :rtype: InlineResponse201
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this InlineResponse201.

        :return: The name of this InlineResponse201.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this InlineResponse201.

        :param name: The name of this InlineResponse201.
        :type name: str
        """

        self._name = name

    @property
    def type(self) -> str:
        """
        Gets the type of this InlineResponse201.

        :return: The type of this InlineResponse201.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """
        Sets the type of this InlineResponse201.

        :param type: The type of this InlineResponse201.
        :type type: str
        """

        self._type = type

    @property
    def properties(self) -> object:
        """
        Gets the properties of this InlineResponse201.

        :return: The properties of this InlineResponse201.
        :rtype: object
        """
        return self._properties

    @properties.setter
    def properties(self, properties: object):
        """
        Sets the properties of this InlineResponse201.

        :param properties: The properties of this InlineResponse201.
        :type properties: object
        """

        self._properties = properties

