# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class TopologydeploymentlocationsnameinstancesProperties(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, property_name: str=None, property_value: str=None):
        """
        TopologydeploymentlocationsnameinstancesProperties - a model defined in Swagger

        :param property_name: The property_name of this TopologydeploymentlocationsnameinstancesProperties.
        :type property_name: str
        :param property_value: The property_value of this TopologydeploymentlocationsnameinstancesProperties.
        :type property_value: str
        """
        self.swagger_types = {
            'property_name': str,
            'property_value': str
        }

        self.attribute_map = {
            'property_name': 'propertyName',
            'property_value': 'propertyValue'
        }

        self._property_name = property_name
        self._property_value = property_value

    @classmethod
    def from_dict(cls, dikt) -> 'TopologydeploymentlocationsnameinstancesProperties':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The topologydeploymentlocationsnameinstances_properties of this TopologydeploymentlocationsnameinstancesProperties.
        :rtype: TopologydeploymentlocationsnameinstancesProperties
        """
        return deserialize_model(dikt, cls)

    @property
    def property_name(self) -> str:
        """
        Gets the property_name of this TopologydeploymentlocationsnameinstancesProperties.

        :return: The property_name of this TopologydeploymentlocationsnameinstancesProperties.
        :rtype: str
        """
        return self._property_name

    @property_name.setter
    def property_name(self, property_name: str):
        """
        Sets the property_name of this TopologydeploymentlocationsnameinstancesProperties.

        :param property_name: The property_name of this TopologydeploymentlocationsnameinstancesProperties.
        :type property_name: str
        """

        self._property_name = property_name

    @property
    def property_value(self) -> str:
        """
        Gets the property_value of this TopologydeploymentlocationsnameinstancesProperties.

        :return: The property_value of this TopologydeploymentlocationsnameinstancesProperties.
        :rtype: str
        """
        return self._property_value

    @property_value.setter
    def property_value(self, property_value: str):
        """
        Sets the property_value of this TopologydeploymentlocationsnameinstancesProperties.

        :param property_value: The property_value of this TopologydeploymentlocationsnameinstancesProperties.
        :type property_value: str
        """

        self._property_value = property_value

